name: tagify_app
description: "Sistema de Gestão de Armazém - ARMAZÉM"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # API e Networking
  http: ^1.2.0
  
  # Gestão de Estado
  provider: ^6.1.0
  
  # Base de Dados Offline
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Scanners
  mobile_scanner: ^5.2.3  # QR Code e Barcode
  camera: ^0.11.0+2       # Câmara para AR
  nfc_manager: ^4.1.1     # NFC Scanner
  
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/sql/TABELAS.sql